### ISSUE TITLE
[Bug]: When routing client-side <Meta /> doesn't update SEO Meta Tags

### ISSUE THREAD

**Issue by JonatanSalas** [remix-run/remix#1028]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.6

### What version of Node are you using? Minimum supported version is 14.

v14.17.1

### Steps to Reproduce

1. Create 2 routes, the First route should go to Second route and viceversa.
2. In each route export a `MetaFunction` with its corresponding metadata.
3. Run the application and move from one route to another.

 If you want to check it out, you can go to https://crypto-remote.com and test it, but for easy check I've uploaded a video showing the issue:

https://user-images.githubusercontent.com/7697196/145892958-ec94a29c-4a72-4839-8a8f-1b0647f07021.mp4

### Expected Behavior

When routing from one page to another if metadata is different it should be updated accordangly. Currently metadata only gets updated if I perform a full page reload.
 
### Actual Behavior

When routing from one page to another metadata isn't getting updated.

**Comment by MarkusWendorf** [comment]
It seems like there's a <title> Tag that is not rendered / managed by React. For html nodes that are handled by React you should see properties like this:
<img width="708" alt="Screenshot 2021-12-14 at 23 27 00" src="https://user-images.githubusercontent.com/18446907/146090537-70e71162-a139-4a4f-b9e6-9fbb441e22d7.png">

The first title does not have these properties, so my guess would be that this <title> tag is rendered by inserting a raw string into the markup, not by means of React.

This would explain why the initial load works but subsequent navigations do not (because React is unaware).

Just a guess

**Comment by machour** [comment]
It seems indeed that there are two titles on the page, and one is not managed by remix.
Closing this for now, please provide a small reproduce case as a repo is you still think something is wrong with remix.
