### ISSUE TITLE
🗺 Remix on Router v6.4

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix#4485]
🚧 [Project Board](https://github.com/orgs/remix-run/projects/10)

Updating Remix's React Router dependency to v6.4, which includes all data loading, mutations, error handling, rendering etc., but does not include streaming/deferred (that's in a different issue).

It also includes all the new APIs like `useRevalidator`, simplified `fetcher` objects, stable route `shouldRevalidate`, etc.

## Decision Doc

https://github.com/remix-run/remix/blob/main/decisions/0007-remix-on-react-router-6-4-0.md

This is being done in a multi-step process to keep risk low and allow for incremental merged/deployments and avoid a single big-bang release (blog post [here](https://remix.run/blog/react-routering-remix)).  Therefore we'll have a few experimental and prereleases covering different aspects of the decision doc.

## Progress

- [x] RFC n/a
- [x] Prerelease
   - [x] Server Data Loading - `0.0.0-experimental-5b4bceda6`
   - [x] Server Rendering + Client Hydration - `0.0.0-experimental-b3829ed22`
- [x] Enabled on dev branch

## Issues/PRs

#4245 #4359 #4385

**Comment by jaschaio** [comment]
Pretty sad about this as it basically means remix won't support `useBlocker` and `usePrompt` any longer. This is a very controversial discussion over here: https://github.com/remix-run/react-router/issues/8139#issuecomment-1262630360

**Comment by ryanflorence** [comment]
Doesn’t mean that at all, but let’s that discussion over there :)

**Comment by machour** [comment]
@laurencefass Remix is currently being rewritten on top of react-router. That work is not released yet.

**Comment by kiliman** [comment]
@laurencefass Remix has always used React Router 6. They built all the data loading functionality separately. Now that they moved that functionality to RR 6.4+, they are updating Remix to use those APIs instead. So Remix will be more of a server implementation of React~~ Remix Router. Remix Router is the platform-agnostic version of React Router since routing is not intrinsically tied to React. They've already built a Vue version, etc.

**Comment by sergiodxa** [comment]
@laurencefass it has always been on the package.json, you're just checking the incorrect one, here's imported https://github.com/remix-run/remix/blob/8f7100b2d5c40d5b2f0856958898cab70ef9d407/packages/remix-react/package.json#L20

As you can see, right now is locked to v6.3.0, after the release of Remix they released Remix Router which is a framework agnostic router, and then made React Router v6.4.0 use Remix Router.

After the work on this issue is completed Remix will be using React Router v6.4

**Comment by sergiodxa** [comment]
> Will this (eventually) provide Suspense boundaries for server fetched/rendered components?

If you're using React v18 you can use Suspense on SSR, but Remix doesn't support React Server Components so if you add any data-fetching inside your components that will happen in the client too.

But you can use Suspense to lazy-load components based on data you fetched on your loader.

Also, it's generally better to keep data fetching at the route level, since that will help you avoid waterfall of requests, if you used RSC and fetch on render, you should have to prefetch all the data somewhere (like at the route level 😉) anyway to prevent the waterfall.

When #4486 is added to Remix (which is tied to this issue) you'll be able to start fetching data on your loaders but send a response immediately without waiting for the data, then use Suspense to render a fallback UI until that part of data is ready.

**Comment by ryanflorence** [comment]
Just FYI, we're locking this and all *roadmap issues*. Our team needs to communicate with each other on these issues so we need to keep the good-but-off-topic comments out of them.

We are happy to answer questions in the discussions tab and discord!

**Comment by brophdawg11** [comment]
This is merged to `dev` and available in `0.0.0-experimental-b3829ed22`.  Should have a `1.10.0` prerelease out tomorrow
