### ISSUE TITLE
[BREAKING]: Remove v1 meta implementation and make v2 default

### ISSUE THREAD

**Issue by chaance** [remix-run/remix#5617]
- [ ] v1 - Add warning if not using the flag
- [ ] v2 - Remove old API and warning
- [ ] v2 - Review types to ensure it's clear where users are expected to import from
